layout_spectrum: 0.6057626374531537
typography_spectrum: 0.8990954000037163
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.8125
  lightness: 0.9099222416989505
  saturation: 0.9320989951957017
  rhythmicContrast: 0.984281322453171
name: Free Personal Finance Software
favicon: null
navigation:
  - name: FAQs
    id: 453c66fc-f1a1-4741-9073-ab0619d5ec28
    type: content
title: FPFS is (almost) here
description: Let us help you take control of your financial life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
